[workspace]
resolver = "2"
members = [
    "./crates/cli",
    "./crates/datagen-rs",
    "./crates/datagen-wasm",
    "./crates/build-vars",
    "./plugins/log-plugin",
    "./plugins/openaddresses-plugin",
    "./plugins/progress-plugin",
    "./plugins/upload-plugin",
    "./plugins/node-plugin",
    "./packages/datagen"
]

[profile.release]
lto = true
