[workspace]
resolver = "2"
members = [
    "./cli",
    "./datagen-rs",
    "./datagen-wasm",
    "./plugins/log-plugin",
    "./plugins/openaddresses-plugin",
    "./plugins/progress-plugin",
    "./plugins/datagen-node"
]

[profile.release]
lto = true
