[package]
edition = "2021"
name = "datagen-node"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { git = "https://github.com/napi-rs/napi-rs", version = "2.13.3", default-features = false, features = [
    "napi8",
    "deferred_trace",
    "async",
    "serde-json"] }
napi-derive = "2.13.0"
datagen-rs = { path = "../../crates/datagen-rs", features = ["all"] }
datagen-rs-progress-plugin = { path = "../../plugins/progress-plugin" }
datagen-rs-node-runner = { path = "../../crates/node-runner" }
serde_json = "1.0"
futures = "0.3"
anyhow = "1"

[build-dependencies]
napi-build = "2.0.1"

#[profile.release]
#lto = true
