[package]
edition = "2021"
name = "datagen-node"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.13", default-features = false, features = [
    "napi8",
    "deferred_trace",
    "async",
    "serde-json"] }
napi-derive = "2.13"
datagen-rs = { path = "../../crates/datagen-rs", features = ["all"] }
datagen-rs-progress-plugin = { path = "../../plugins/progress-plugin" }
serde_json = "1.0"
futures = "0.3"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
