FROM rust:1-bookworm as builder

ADD . /app
WORKDIR /app

RUN cargo build -p datagen-rs-cli -r --no-default-features

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/datagen /usr/local/bin/datagen
COPY --from=builder /app/docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
