FROM rust:1-bookworm as builder

ADD . /app
WORKDIR /app

RUN cargo build -p datagen-rs-cli -r --no-default-features

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/datagen /usr/local/bin/datagen

ENTRYPOINT ["/usr/local/bin/datagen"]