name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
    - name: Build cli
      run: cargo build --package cli --release
    - name: Build openaddresses plugin
      run: cargo build --package openaddresses-plugin --release --features sqlite
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: datagen-${{runner.os}}
        path: |
          target/release/cli.exe
          target/release/cli
          target/release/openaddresses_plugin.dll
          target/release/openaddresses_plugin.dylib
          target/release/openaddresses_plugin.so
