name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        type: string
        required: false
      latest:
        description: 'Latest'
        type: boolean
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datagen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            export TAG=latest
          else
            export TAG=${{ github.event.inputs.tag }}
          fi
          docker build . --file docker/Dockerfile --tag $IMAGE_NAME
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')/$IMAGE_NAME
          
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            export TAG=latest
          else
            if [ "${{ github.event.inputs.latest }}" == "true" ]; then
              docker tag $IMAGE_NAME $IMAGE_ID:latest
              docker push $IMAGE_ID:latest
            fi
          
            export TAG=${{ github.event.inputs.tag }}
          fi
          docker tag $IMAGE_NAME $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG
      - name: Push latest image
        if: ${{ github.event.inputs.latest == 'true' }}
        run: docker push ghcr.io/datagen:latest
