name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
        with:
          key: clippy
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

  lint-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            ./packages/datagen/package-lock.json
            ./packages/cli/package-lock.json
            ./packages/types/package-lock.json

      - name: Install datagen-node dependencies
        run: npm ci
        working-directory: packages/datagen
      - name: Lint datagen-node
        run: npm run lint
        working-directory: packages/datagen

      - name: Install node-cli dependencies
        run: npm ci
        working-directory: packages/cli
      - name: Lint node-cli
        run: npm run lint
        working-directory: packages/cli

      - name: Install types dependencies
        run: npm ci
        working-directory: packages/types
      - name: Lint types
        run: npm run lint
        working-directory: packages/types

      - name: Install version-check dependencies
        run: npm ci
        working-directory: packages/version-check
      - name: Lint version-check
        run: npm run lint
        working-directory: packages/version-check

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./docs/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: docs
      - name: Lint docs
        run: npm run lint
        working-directory: docs
      - name: Check links
        if: github.ref != 'refs/heads/main'
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: docs/pages
          file-extension: .md*

  lint-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./packages/version-check/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: packages/version-check
      - name: Lint versions
        run: npm run lint
        working-directory: packages/version-check
