name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - name: Install nextest
        run: cargo binstall --no-confirm cargo-nextest --secure
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: Run tests
        run: |
          cargo nextest run -p datagen-rs-progress-plugin -p datagen-rs-upload-plugin \
          -p datagen-rs-openaddresses-plugin --features sqlite -p datagen-rs --features all \
          -P ci
      - name: Run doc tests
        run: cargo test --doc
      - name: Create test summary
        uses: test-summary/action@dist
        if: always()
        with:
          show: all
          paths: target/nextest/ci/junit.xml

  test-node:
    strategy:
        matrix:
            node-version: [ 16.x, 18.x ]
            os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: Install types dependencies
        run: npm ci
        working-directory: packages/types
      - name: Install dependencies
        run: npm ci
        working-directory: packages/datagen
      - name: Run tests
        run: npm test
        working-directory: packages/datagen
