name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cargo-bins/cargo-binstall@main
      - name: Install nextest
        run: cargo binstall cargo-nextest --secure
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: Test datagen-rs
        run: cargo nextest run --p datagen-rs --features all --lib
